# Generated by Django 5.0.6 on 2026-05-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('PANTS', 'Calça'), ('T_SHIRT', 'Camiseta'), ('SHIRT', 'Camisa Social'), ('REGULAR_SHIRT', 'Camisa'), ('POLO', 'Camisa Polo'), ('JACKET', 'Jaqueta'), ('COAT', 'Casaco'), ('SWEATER', 'Suéter'), ('SHOES', 'Sapato/Tênis'), ('ACCESSORY', 'Acessórios')], max_length=20),
        ),
    ]
