# Generated by Django 5.0.6 on 2026-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clothingitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='last_used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
